require ( "settings" )
require ( "packer-config" )
require ( "colorschemes-config.gruvbox")
require ( "nvim-tree-config" )
require ( "mappings" )
require ( "lsp-config.language-servers" )
require ( "autopairs-config" )
require ( "toggleterm-config" )
require ( "lsp-config.nvim-cmp")
